class SongbirdError(Exception):
    ...


class UseAsyncConstructorError(SongbirdError):
    ...
class CouldNotConnectToRTPError(SongbirdError):
    ...
class CouldNotOpenFileError(SongbirdError):
    ...
class YtdlError(SongbirdError):
    ...
class FfmpegError(SongbirdError):
    ...
